### ISSUE TITLE
Defaults on the outside of a FlatMap don't get used

### ISSUE THREAD

**Issue by kubukoz** [vlovgr/ciris#776]
Hi! I've stumbled upon an interesting issue that breaks my expectations a bit. It could be intentional or not.

Let me start with the code:

```scala
//> using dep is.cir::ciris::3.6.0
//> using dep org.typelevel::cats-effect:3.5.4
//> using option -Wunused:all
import cats.effect.IO
import cats.effect.IOApp
import ciris.*

object Demo extends IOApp.Simple {

  val ok = env("WHATEVER").flatMap(_ => env("VAR_A").default(""))

  val notOk = env("WHATEVER").flatMap(_ => env("VAR_A")).default("")

  def run: IO[Unit] =
    (
      ok.load[IO].debug("ok") *>
        notOk.load[IO].debug("notOk"),
    ).attempt.void

}
```

Assume the following environment: `WHATEVER=test`.

The printed result is:

```
ok: Succeeded: 
notOk: Errored: ciris.ConfigException: configuration loading failed with the following errors.

  - Missing environment variable VAR_A.
```

To sum up, `ok` is fine because the default is applied directly on `env`. `notOk` is not fine because the default is applied on the result of flatMapping. In my real scenario, this looked more like this:

```scala
env("ENVIRONMENT").flatMap {
  case "local" =>
    (
      env("k1"),
      env("k2")
    ).parTupled.option
}
```

but the underlying cause was the same. My expectation was to see it succeed (and the `option` / `default` to be applied).

Note: the expected behavior is happening if `env("WHATEVER")` is inlined into `default("test")`, which suggests to me that something is not right here.

**Comment by kubukoz** [comment]
I believe the culprit is here:

```scala
  final def default(value: => A): ConfigValue[F, A] =
    transform {
      case Default(error, _)                => Default(error, value)
      case Failed(error) if error.isMissing => Default(error, value)
      case failed @ Failed(_)               => failed
      case loaded @ Loaded(_, _, _)         => loaded
    }
```

the parameter to the lambda is `"Failed(And(Loaded, Missing(ConfigKey(environment variable VAR_A))))"`, which doesn't pass the `isMissing` check as that's implemented with:

```scala
case And(errors)     => errors.forall(_.isMissing)
```

**Comment by vlovgr** [comment]
Hi,

There is some history on `flatMap` in https://github.com/vlovgr/ciris/issues/375 which could be worth reading.

The behaviour is intentional and I believe this is more about what `flatMap` is supposed to represent (there's ongoing work in https://github.com/vlovgr/ciris/pull/770 towards getting rid of `flatMap` and further upcoming work to use `Selective` instead). Let's take a look at your examples below.

```scala
val ok = env("WHATEVER").flatMap(_ => env("VAR_A").default(""))
```

The above reads:

- if env WHATEVER is set:
  - load a second env VAR_A:
    - if env VAR_A is present, use its value,
    - if env VAR_A is missing, use the empty string,
- if env WHATEVER is missing, raise an error.

```scala
val notOk = env("WHATEVER").flatMap(_ => env("VAR_A")).default("")
```

The above reads: 

- If env WHATEVER is set:
  - load a second env VAR_A:
    - if env VAR_A is present, use its value,
    - if env VAR_A is missing, raise an error,
- If env WHATEVER is missing, use the empty string.

The intution behind the following example:

```scala
(env("k1"), env("k2")).parTupled.option
```

should be "if both env k1 and env k2 are missing, use `None`".

> Note: the expected behavior is happening if `env("WHATEVER")` is inlined into `default("test")`, which suggests to me that something is not right here. 

It's worth noting `env(x)` will never return a default value (`ConfigValue.default`), only `ConfigValue.loaded` or `ConfigValue.missing`. The loaded and default cases behave differently when it comes to default values (briefly described in the [documentation](https://cir.is/docs/configurations#defaults)).
